# -*- coding: utf-8 -*-
"""Reimagining customer experience with emerging technologies.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sJ1n76w8aViDHocu_mQm0zIeerwqi5qt
"""
import streamlit as st
import pandas as pd

# Load and clean data
df = pd.read_csv("retail_products_100.csv")
df["numeric_price"] = df["price"].str.replace("₹", "").str.replace(",", "").astype(int)

# Page config and background styling
st.set_page_config(page_title="🛍️ SmartShop AI", layout="wide")
st.markdown(
    '''
    <style>
    body {
        background: linear-gradient(to right, #ff7e5f, #feb47b);
        font-family: 'Arial', sans-serif;
    }
    .big-title {
        font-size: 3em;
        font-weight: bold;
        color: #ffffff;
        text-align: center;
        text-shadow: 2px 2px 4px rgba(0, 0, 0, 0.5);
    }
    .tagline {
        font-size: 1.5em;
        font-weight: 500;
        text-align: center;
        color: #ffffff;
        margin-bottom: 20px;
    }
    .motion-box {
        transition: transform 0.3s;
        border-radius: 15px;
        padding: 20px;
        background-color: rgba(255, 255, 255, 0.9);
        box-shadow: 0 4px 20px rgba(0, 0, 0, 0.1);
    }
    .motion-box:hover {
        transform: scale(1.05);
    }
    </style>
    ''',
    unsafe_allow_html=True
)

# Header
st.markdown('<div class="big-title">SmartShop 🛒</div>', unsafe_allow_html=True)
st.markdown('<div class="tagline">Your AI-powered fashion and product companion ✨</div>', unsafe_allow_html=True)
st.markdown("#### Ask anything like 'red shoes under 2000 for gym' or just pick your budget from below")

# Chat input
query = st.chat_input("Type your shopping intent (e.g. waterproof shoes for gym under 1500)")

# Price filter dropdown
price_limit = st.selectbox("Or choose a price limit:", [None, 1000, 1500, 2000, 2500, 3000], index=0)

# Generate AI-style response
def generate_response(q):
    q = q.lower()
    if "budget" in q or "under" in q:
        return "💸 Here's what I found for your price range:"
    elif "eco" in q or "recycled" in q:
        return "🌿 Love your choice! Here are some eco-friendly picks:"
    elif "gym" in q:
        return "🏋️ Check out these sporty items for gym-goers!"
    else:
        return "🛍️ Here's what I think you'll love:"

# Filtering logic
def filter_products(q, limit):
    q = q.lower()
    result = df.copy()
    if "gym" in q:
        result = result[result["description"].str.lower().str.contains("gym")]
    if "red" in q:
        result = result[result["color"].str.lower().str.contains("red")]
    if "eco" in q or "recycled" in q:
        result = result[result["description"].str.lower().str.contains("eco|recycled|organic")]
    if "waterproof" in q:
        result = result[result["description"].str.lower().str.contains("waterproof")]
    if any(f"under {p}" in q for p in [1000,1500,2000,2500,3000]):
        val = int([p for p in [1000,1500,2000,2500,3000] if f"under {p}" in q][0])
        result = result[result["numeric_price"] <= val]
    if limit:
        result = result[result["numeric_price"] <= limit]
    return result.head(9)

# Chat interface
if query or price_limit:
    if query:
        with st.chat_message("user"):
            st.markdown(query)
        with st.chat_message("assistant"):
            st.markdown(generate_response(query))
        results = filter_products(query, price_limit)
    else:
        st.markdown("### 💰 Showing products under ₹{}:".format(price_limit))
        results = filter_products("", price_limit)

    if results.empty:
        st.warning("🚫 No products found for your query.")
    else:
        cols = st.columns(3)
        for i, (_, row) in enumerate(results.iterrows()):
            with cols[i % 3]:
                st.markdown('<div class="motion-box">', unsafe_allow_html=True)
                try:
                    st.image(row["image_url"], width=200)
                except:
                    st.image("https://via.placeholder.com/200x200?text=No+Image", width=200)
                st.markdown(f"**{row['title']}**")
                st.markdown(f"💰 ₹{row['numeric_price']}  \n🏷️ {row['category']}")
                st.markdown(f"🎨 {row['color']} | 🧵 {row['material']}")
                st.markdown(f"⭐ {row['rating']}/5")
                st.caption(row["description"])
                st.markdown('</div>', unsafe_allow_html=True)

st.markdown("---")
st.caption("🚀 Built by Team AI Avengers for Walmart Hackathon 2025")

